/**
 * SEO foundation audit for https://www.madrasio.com/
 *
 * Verifies the live routes generated by app/robots.ts, app/sitemap.ts
 * and the canonical tag from the root metadata export:
 *  1. /robots.txt    -> HTTP 200, contains "User-agent: *" and the sitemap URL.
 *  2. /sitemap.xml   -> HTTP 200, XML content-type, contains the homepage URL.
 *  3. /              -> HTML contains <link rel="canonical" href="https://www.madrasio.com/">.
 *
 * Usage:
 *   npm run audit:seo                    # audit production
 *   node scripts/audit-seo.js <baseUrl>  # audit another origin (e.g. local preview)
 *
 * Exit code: 0 when every check passes, 1 otherwise.
 */

const BASE = (process.argv[2] || 'https://www.madrasio.com').replace(/\/$/, '');
const TIMEOUT_MS = 20000;

const EXPECTED_SITEMAP_URL = 'https://www.madrasio.com/sitemap.xml';
const EXPECTED_HOMEPAGE_URL = 'https://www.madrasio.com/';
const EXPECTED_CANONICAL_HREF = 'https://www.madrasio.com';

async function get(path) {
  const url = `${BASE}${path}`;
  const res = await fetch(url, {
    signal: AbortSignal.timeout(TIMEOUT_MS),
    headers: { 'User-Agent': 'Madrasio-SEO-Audit/1.0' },
  });
  const body = await res.text();
  return { url, status: res.status, headers: res.headers, body };
}

function check(name, ok, detail) {
  console.log(`${ok ? 'PASS' : 'FAIL'}  ${name}${detail ? `\n      ${detail}` : ''}`);
  return ok ? 0 : 1;
}

async function main() {
  console.log(`Auditing SEO foundations at ${BASE}\n`);
  let failures = 0;

  // 1. robots.txt
  try {
    const robots = await get('/robots.txt');
    failures += check(
      'robots.txt returns HTTP 200',
      robots.status === 200,
      `GET ${robots.url} -> ${robots.status}`,
    );
    failures += check(
      'robots.txt allows all user-agents',
      /^user-agent:\s*\*/im.test(robots.body),
      'looking for "User-agent: *"',
    );
    failures += check(
      `robots.txt references sitemap (${EXPECTED_SITEMAP_URL})`,
      robots.body.includes(EXPECTED_SITEMAP_URL),
      'looking for the absolute sitemap URL',
    );
  } catch (err) {
    failures += check('robots.txt reachable', false, err.message);
  }
  console.log('');

  // 2. sitemap.xml
  try {
    const sitemap = await get('/sitemap.xml');
    failures += check(
      'sitemap.xml returns HTTP 200',
      sitemap.status === 200,
      `GET ${sitemap.url} -> ${sitemap.status}`,
    );
    const contentType = sitemap.headers.get('content-type') || '';
    failures += check(
      'sitemap.xml served as XML',
      /application\/xml|text\/xml/i.test(contentType),
      `content-type: ${contentType || '(missing)'}`,
    );
    failures += check(
      `sitemap.xml contains homepage (${EXPECTED_HOMEPAGE_URL})`,
      sitemap.body.includes(EXPECTED_HOMEPAGE_URL),
      'looking for the homepage <loc>',
    );
  } catch (err) {
    failures += check('sitemap.xml reachable', false, err.message);
  }
  console.log('');

  // 3. canonical tag on homepage
  try {
    const home = await get('/');
    failures += check(
      'homepage returns HTTP 200',
      home.status === 200,
      `GET ${home.url} -> ${home.status}`,
    );
    const canonicalPattern =
      /<link[^>]*rel=["']canonical["'][^>]*href=["']([^"']+)["'][^>]*>/i;
    const altPattern =
      /<link[^>]*href=["']([^"']+)["'][^>]*rel=["']canonical["'][^>]*>/i;
    const match =
      home.body.match(canonicalPattern) || home.body.match(altPattern);
    const href = match ? match[1].replace(/\/$/, '') : null;
    failures += check(
      `canonical tag points to ${EXPECTED_CANONICAL_HREF}`,
      href === EXPECTED_CANONICAL_HREF,
      match ? `found href="${match[1]}"` : 'no <link rel="canonical"> in <head>',
    );
  } catch (err) {
    failures += check('homepage reachable', false, err.message);
  }

  console.log(
    failures === 0 ? '\nAll SEO checks passed.' : `\n${failures} check(s) FAILED.`,
  );
  process.exit(failures === 0 ? 0 : 1);
}

main().catch((err) => {
  console.error(`Audit crashed: ${err.message}`);
  process.exit(1);
});
